apiVersion: apps/v1
kind: Deployment
metadata:
  name: way
spec:
  replicas: 1
  selector:
    matchLabels:
      app: way
  template:
    metadata:
      labels:
        app: way
    spec:
      containers:
      - image: okteto.dev/way:latest
        name: way
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "03a18a869743.up.railway.app"
        - name: Vless_UUID
          value: "08053b44-f5e7-48e0-bd93-ed2432f25a0e"
        - name: Vless_Path
          value: "/app"
        - name: Vmess_UUID
          value: "08053b44-f5e7-48e0-bd93-ed2432f25a0e"
        - name: Vmess_Path
          value: "/appvmess"
        - name: Share_Path
          value: "/share233"
